language: cpp
compiler:
  - gcc
# - clang
install:
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:boost-latest/ppa
  -
  - sudo apt-get update
  - sudo apt-get install clang-3.4 libboost1.54 g++-4.8 gcc-4.8 build-essential libgtest-dev protobuf-compiler libprotobuf-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - 
  - wget -O botan-1.11_amd64.deb https://dl.dropboxusercontent.com/u/2310050/p2pnet/botan-1.11_amd64.deb
  - sudo dpkg -i botan-1.11_amd64.deb
script:
  - cmake .
  - make
branches:
  only:
    - master
    - travis-config

