language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get dist-upgrade
  - sudo apt-get install ccache monotone libboost-all-dev g++-4.8 gcc-4.8 build-essential python-all binutils-gold
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - cd contrib
  - mkdir downloads
  - cd downloads
  - mtn db init --db=botan.mtn
  - mtn pull --db=botan.mtn mtn.randombit.net 'net.randombit.botan'
  - mtn checkout --db=botan.mtn --branch=net.randombit.botan botan
  - cd botan
  - ./configure.py --prefix=../../
  - make
  - make install
  - cd ../..
  - ls
script:
  - ls
  - cd D_linamd64
  - make all
branches:
  only:
    - master
    - travis-config

