language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:webupd8team/java
  -
  - sudo apt-get update
  - sudo apt-get dist-upgrade
  -
  - echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
  -
  - sudo apt-get install ccache monotone libboost1.48-all-dev g++-4.8 gcc-4.8 build-essential python-all binutils-gold mercurial subversion libgtest-dev protobuf-compiler libprotobuf-dev oracle-java8-installer
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - 
  - cd contrib
  - mkdir downloads
  - cd downloads
  -
  - mtn db init --db=botan.mtn
  - mtn pull --db=botan.mtn mtn.randombit.net 'net.randombit.botan'
  - mtn checkout --db=botan.mtn --branch=net.randombit.botan botan
  - hg clone https://code.google.com/p/cpp-btree/
  - wget -O eclipse.tar.gz "http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/kepler/R/eclipse-cpp-kepler-R-linux-gtk-x86_64.tar.gz&r=1"
  - 
  - tar -xvzf eclipse.tar.gz
  - 
  - cd botan
  - ./configure.py --prefix=../../
  - make
  - make install
  - cd ../..
  - cd ..
  - ls
script:
  - ls
  - contrib/downloads/eclipse/eclipse -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -import . -build p2pnet
branches:
  only:
    - master
    - travis-config

